name: Publish Prerelease APK

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create local.properties
        run: touch local.properties

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run Tests
        run: bash ./gradlew test --stacktrace

      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk

  release:
    name: Release APK
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk

      - name: Rename apk
        run: mv apk/app-debug.apk apk/Ideator.apk

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.ref }} }}
          prerelease: true
          title: Pre-Release ${{ env.VERSION }}
          files: |
            ./apk/Ideator.apk
