name: Test App

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - '**/*.java'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create local.properties
        run: touch local.properties

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run Tests
        run: bash ./gradlew test --stacktrace
